version: "3.9"

services:
  backend:
    build: ./store-availability-api
    ports:
      - "8000:8000"
    env_file:
      - ./store-availability-api/.env

  frontend:
    build: ./store-availability-dashboard
    ports:
      - "5173:5173"
    env_file:
      - ./store-availability-dashboard/.env
    depends_on:
      - backend